using System;

namespace EnKolayCari.Application.Model.DTO.Common
{
    public class CompanyDto
    {
        public long Id { get; set; }
        public Guid GId { get; set; }
        public bool Stat { get; set; }
        public string Code { get; set; }
        public string City { get; set; }
        public bool IsActivationCompleted { get; set; }
        public DateTime? ActivationDate { get; set; }
        public string Title { get; set; }
        public string Email { get; set; }
        public string WebsiteUrl { get; set; }
        public string Address { get; set; }
        public string District { get; set; }
        public string MapUrl { get; set; }
        public string TaxOffice { get; set; }
        public string TaxNumber { get; set; }
        public string Phone1 { get; set; }
        public string Phone2 { get; set; }
        public string Fax { get; set; }
        public string AuthorizedPerson { get; set; }
        public string DefaultCurrencyCode { get; set; }
        public string CurrencyCodes { get; set; }
        public string Parameters { get; set; }
        public long? LegacyServerId { get; set; }
        public int WeightBarcodeLength { get; set; }
        public int WeightBarcodeDecimalLength { get; set; }
        public int? Integrator { get; set; }
        public string IntegratorUserName { get; set; }
        public string IntegratorPassword { get; set; }
        public int? UserCount { get; set; }
        public string AboutUs { get; set; }
        public string ColorSizeLabel { get; set; }
        public string EcommerceStyle { get; set; }
        public string EcommerceStylePrefix { get; set; }
        public string FavIconPrefix { get; set; }
        public string EcommerceStyle1 { get; set; }
        public string EcommerceStylePrefix1 { get; set; }
        public string FavIconPrefix1 { get; set; }
        public decimal FreeShippingLimit { get; set; }
        public decimal? WeightServiceFee { get; set; }
        public decimal? DesiServiceFee { get; set; }
        public decimal ShippingFee { get; set; }
        public string ShippingLabel { get; set; }
        public string FacebookUrl { get; set; }
        public string InstagramUrl { get; set; }
        public string TwitterUrl { get; set; }
        public string PinterestUrl { get; set; }
        public string YoutubeUrl { get; set; }
        public bool? IsBankTransferActive { get; set; }
        public bool? IsCashOnDeliveryActive { get; set; }
        public string EcommerceSiteName { get; set; }
        public string ShowcaseName { get; set; }
        public string ShowcaseLabel { get; set; }
        public string GoogleAnalyticsId { get; set; }
        public string FacebookPixelId { get; set; }
        public string WhatsAppPhone { get; set; }
        public bool IsSslActive { get; set; }
        public bool IsWideTopMenuActive { get; set; }
        public bool AllProductsMainMenuActive { get; set; }
        public bool AllProductsSubMenuActive { get; set; }
        public int ProductImageWidth { get; set; }
        public int ProductImageHeight { get; set; }
        public string SeoKeywords { get; set; }
        public bool GenerateSitemap { get; set; }
        public bool HideCategoryText { get; set; }
        public bool ShowAllStores { get; set; }
        public bool ShowAllCashRegisters { get; set; }
        public string TrendyolSellerId { get; set; }
        public string TrendyolApiKey { get; set; }
        public string TrendyolApiSecret { get; set; }
        public bool ShowColorSizeOnProductScreen { get; set; }
        public decimal FirstPurchaseDiscountPercent { get; set; }
        public bool? UseOwnMailSettings { get; set; }
        public string MailAddress { get; set; }
        public string MailDisplayName { get; set; }
        public string MailUserName { get; set; }
        public string MailPassword { get; set; }
        public string MailHost { get; set; }
        public int? MailPort { get; set; }
        public bool? IsDynamicExchangeRate { get; set; }
        public int LogoHeight { get; set; }
        public string MersisNumber { get; set; }
        public string TradeRegistryNumber { get; set; }
        public bool ImportExternalData { get; set; }
        public string ExternalSystemName { get; set; }
        public string ExternalSystemIp { get; set; }
        public string ExternalSystemDb { get; set; }
        public string ExternalSystemUser { get; set; }
        public string ExternalSystemPassword { get; set; }
        public string IntegratorEInvoiceTemplate { get; set; }
        public string IntegratorEArchiveTemplate { get; set; }
        public string SmsPhoneNumber { get; set; }
        public string SmsTitle { get; set; }
        public string SmsUserName { get; set; }
        public string SmsPassword { get; set; }
        public string AppointmentFirstSms { get; set; }
        public string AppointmentChangeSms { get; set; }
        public string AppointmentCancelForceSms { get; set; }
        public string AppointmentCancelPatientSms { get; set; }
        public string AppCode { get; set; }
        public DateTime? InsertDateTime { get; set; }
        public long? UpdateUser { get; set; }
        public DateTime? UpdateDateTime { get; set; }
        public long? DeleteUser { get; set; }
        public DateTime? DeleteDateTime { get; set; }
    }
}
