<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net9.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.AspNetCore.Authentication.JwtBearer" Version="9.0.9" />
    <PackageReference Include="Swashbuckle.AspNetCore" Version="9.0.6" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\EnKolayCari2026.Application.Services\EnKolayCari2026.Application.Services.csproj" />
    <ProjectReference Include="..\EnKolayCari2026.Application.Services.Model\EnKolayCari2026.Application.Services.Model.csproj" />
    <ProjectReference Include="..\EnKolayCari2026.Application.Model\EnKolayCari2026.Application.Model.csproj" />
    <ProjectReference Include="..\EnKolayCari2026.Language\EnKolayCari2026.Language.csproj" />
  </ItemGroup>

</Project>
